In [63]:
import geopandas as gpd
import pandas as pd
from pathlib import Path
from shapely.geometry import box
import numpy as np
import folium
from datetime import datetime

# Arquivos obtidos no GEOSAMPA - Dados históricos desde 2013
pasta = Path("SIRGAS_GPKG_riscoocorrencia")

# Leitura dos arquivos e unificação em uma única variável
dados = []

for arquivo in pasta.glob("*.gpkg"):

    gdf_temp = gpd.read_file(arquivo)

    gdf_temp = gdf_temp.to_crs("EPSG:31983")

    dados.append(gdf_temp)

gdf = pd.concat(dados, ignore_index=True)

c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(

In [64]:
# Garantir que a data está em formato datetime
gdf["data"] = pd.to_datetime(gdf["data"])

# Extrair o ano da ocorrência
gdf["ano"] = gdf["data"].dt.year

In [65]:
# Definição dos pesos temporais
pesos = {
    ano: peso
    for peso, ano in enumerate(range(2013, 2027), start=1)
}

# Aplicação do peso
gdf["peso_ano"] = gdf["ano"].map(pesos)

# Captura dos limites de coordenadas
xmin, ymin, xmax, ymax = gdf.total_bounds

# Definição de que o mapa completo será dividido em quadrados de 250m x 250m
tamanho = 250

grid = []

# Criação dos quadrados
for x in np.arange(xmin, xmax, tamanho):

    for y in np.arange(ymin, ymax, tamanho):

        grid.append(
            box(
                x,
                y,
                x + tamanho,
                y + tamanho
            )
        )

In [66]:
# Transformação em GeoDataFrame
grid = gpd.GeoDataFrame(
    geometry=grid,
    crs="EPSG:31983"
)

# Identificação dos pontos dentro dos quadrados
join = gpd.sjoin(
    gdf,
    grid,
    predicate="within"
)

# Quantidade de ocorrências
contagem = (
    join
    .groupby("index_right")
    .size()
)

In [67]:

# Soma dos pesos temporais
score_temporal = (
    join
    .groupby("index_right")["peso_ano"]
    .sum()
)

# Quantidade de anos distintos com ocorrência
anos_distintos = (
    join
    .groupby("index_right")["ano"]
    .nunique()
)

# Inicialização dos campos
grid["ocorrencias"] = 0
grid["score"] = 0
grid["anos_distintos"] = 0

# Preenchimento dos resultados
grid.loc[
    contagem.index,
    "ocorrencias"
] = contagem.values

grid.loc[
    score_temporal.index,
    "score"
] = score_temporal.values

grid.loc[
    anos_distintos.index,
    "anos_distintos"
] = anos_distintos.values

In [68]:
# Classificação considerando recorrência temporal
def classificar(score, anos):

    # Ocorrência em praticamente toda a série histórica
    if anos >= 10:
        return "CRITICO"

    if score >= 120:
        return "CRITICO"

    if score >= 60:
        return "ALTO"

    if score >= 20:
        return "MEDIO"

    return "BAIXO"

grid["risco"] = grid.apply(
    lambda row: classificar(
        row["score"],
        row["anos_distintos"]
    ),
    axis=1
)

# Filtra áreas com mais de uma ocorrência
grid = grid[
    grid["ocorrencias"] > 1
].copy()

# Conversão para WGS84
grid = grid.to_crs(4326)

In [69]:
# Visualização do objeto criado
grid

,geometry,ocorrencias,score,anos_distintos,risco
483,"POLYGON ((-46.81813 -23.41262, -46.81809 -23.4...",2,23,2,MEDIO
1475,"POLYGON ((-46.80871 -23.43982, -46.80868 -23.4...",5,43,2,MEDIO
1485,"POLYGON ((-46.8084 -23.41725, -46.80837 -23.41...",3,25,3,MEDIO
1725,"POLYGON ((-46.8063 -23.44211, -46.80626 -23.43...",2,18,2,BAIXO
1726,"POLYGON ((-46.80626 -23.43985, -46.80623 -23.4...",11,108,5,ALTO
...,...,...,...,...,...
46879,"POLYGON ((-46.36651 -23.50528, -46.36649 -23.5...",4,28,4,MEDIO
46881,"POLYGON ((-46.36647 -23.50076, -46.36644 -23.4...",3,28,3,MEDIO
47128,"POLYGON ((-46.36411 -23.50982, -46.36409 -23.5...",2,23,2,MEDIO
47129,"POLYGON ((-46.36409 -23.50756, -46.36406 -23.5...",2,6,2,BAIXO
47130,"POLYGON ((-46.36406 -23.5053, -46.36404 -23.50...",2,22,2,MEDIO

In [70]:
#Export para possível utilização futura
grid.to_file(
    "risco.geojson",
    driver="GeoJSON"
)

In [71]:
# Centralização do mapa
centro = [
    grid.geometry.centroid.y.mean(),
    grid.geometry.centroid.x.mean()
]

# Criação do mapa
m = folium.Map(
    location=centro,
    zoom_start=11,
    tiles="CartoDB positron"
)

C:\Users\F8709919\AppData\Local\Temp\ipykernel_5700\1125207210.py:3: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  grid.geometry.centroid.y.mean(),
C:\Users\F8709919\AppData\Local\Temp\ipykernel_5700\1125207210.py:4: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  grid.geometry.centroid.x.mean()
c:\Users\F8709919\AppData\Local\Programs\Python\Python311\Lib\site-packages\folium\raster_layers.py:130: UserWarning: CartoDB tiles now require an API key. Please provide one to continue using the tiles. You can request the key at https://carto.com/basemaps/apikey/.
  tiles = tiles.build_url(fill_subdomain=False, scale_factor="{r}")  # type: ignore

In [72]:
# Estilo baseado no risco
def estilo(feature):

    risco = feature["properties"]["risco"]

    cores = {
        "BAIXO": "#00AA00",
        "MEDIO": "#FFFF00",
        "ALTO": "#FF8800",
        "CRITICO": "#FF0000"
    }

    return {
        "fillColor": cores.get(risco, "#808080"),
        "color": "#000000",
        "weight": 1,
        "fillOpacity": 0.6
    }

In [73]:
# Adiciona os polígonos ao mapa
folium.GeoJson(
    grid,
    style_function=estilo,
    tooltip=folium.GeoJsonTooltip(
        fields=[
            "risco",
            "ocorrencias",
            "anos_distintos",
            "score"
        ],
        aliases=[
            "Risco:",
            "Ocorrências:",
            "Anos distintos:",
            "Score temporal:"
        ]
    )
).add_to(m)

# Salva o mapa
m.save("mapa_risco_atualizado.html")

In [74]:
grid.columns

Index(['geometry', 'ocorrencias', 'score', 'anos_distintos', 'risco'], dtype='object')

In [75]:
grid

,geometry,ocorrencias,score,anos_distintos,risco
483,"POLYGON ((-46.81813 -23.41262, -46.81809 -23.4...",2,23,2,MEDIO
1475,"POLYGON ((-46.80871 -23.43982, -46.80868 -23.4...",5,43,2,MEDIO
1485,"POLYGON ((-46.8084 -23.41725, -46.80837 -23.41...",3,25,3,MEDIO
1725,"POLYGON ((-46.8063 -23.44211, -46.80626 -23.43...",2,18,2,BAIXO
1726,"POLYGON ((-46.80626 -23.43985, -46.80623 -23.4...",11,108,5,ALTO
...,...,...,...,...,...
46879,"POLYGON ((-46.36651 -23.50528, -46.36649 -23.5...",4,28,4,MEDIO
46881,"POLYGON ((-46.36647 -23.50076, -46.36644 -23.4...",3,28,3,MEDIO
47128,"POLYGON ((-46.36411 -23.50982, -46.36409 -23.5...",2,23,2,MEDIO
47129,"POLYGON ((-46.36409 -23.50756, -46.36406 -23.5...",2,6,2,BAIXO
47130,"POLYGON ((-46.36406 -23.5053, -46.36404 -23.50...",2,22,2,MEDIO

In [76]:
# Seleciona apenas as colunas necessárias
exportacao = grid.copy()
exportacao = exportacao[['geometry', 'ocorrencias', 'risco']]
# Renomeação de acordo com nomenclatura do bd
exportacao = exportacao.rename(
    columns={
        "geometry": "poligono",
        "ocorrencias": "indice_ocorrencias",
        "risco": "nivel_risco"
    }
)

# Reset para coluna geométrica
exportacao = exportacao.set_geometry("poligono")

# Campo fixo
exportacao["fonte_dados"] = "geo_sampa"

# Timestamp da carga
exportacao["ultima_atualizacao"] = datetime.now()

# Garantir WGS84
exportacao = exportacao.to_crs(4326)

In [77]:
# Conexão com BD
from sqlalchemy import create_engine

DATABASE_URL = ("postgresql://postgres:alagaweb0111@db.vapquaogbccjekvlpzhg.supabase.co:5432/postgres")

engine = create_engine(DATABASE_URL)

In [78]:
# Exportacao BD
exportacao.to_postgis(
    name="regioes",
    con=engine,
    if_exists="replace",
    index=False
)